/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo46.Vistas;

/**
 *
 * @author simon
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JItemGestionAlumno = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGestionMat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemFormInscripciones = new javax.swing.JMenuItem();
        ManipulacionDeNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAxMat = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        JItemGestionAlumno.setSelected(true);
        JItemGestionAlumno.setText("Formulario de alumno");
        JItemGestionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemGestionAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(JItemGestionAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jMenuItemGestionMat.setText("Formulario de materia");
        jMenuItemGestionMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionMatActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGestionMat);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        jMenuItemFormInscripciones.setText("Manejo de inscripciones");
        jMenuItemFormInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemFormInscripciones);

        ManipulacionDeNotas.setText("Manipulacion de notas");
        ManipulacionDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManipulacionDeNotasActionPerformed(evt);
            }
        });
        jMenu3.add(ManipulacionDeNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuItemAxMat.setText("Alumnos por materia");
        jMenuItemAxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAxMatActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAxMat);

        jMenuBar1.add(jMenu4);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFormInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormInscripcionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeInscripciones FormIns = new FormularioDeInscripciones();
        FormIns.setVisible(true);
        escritorio.add(FormIns);
        escritorio.moveToFront(FormIns);
    }//GEN-LAST:event_jMenuItemFormInscripcionesActionPerformed
    
    private void ManipulacionDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManipulacionDeNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ActualisacionDeNotas mdn = new ActualisacionDeNotas();
        mdn.setVisible(true);
        escritorio.add(mdn);
        escritorio.moveToFront(mdn);
    }//GEN-LAST:event_ManipulacionDeNotasActionPerformed
    
    private void JItemGestionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemGestionAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionAlumno ga = new GestionAlumno();
        ga.setVisible(true);
        escritorio.add(ga);
        escritorio.moveToFront(ga);
    }//GEN-LAST:event_JItemGestionAlumnoActionPerformed
    
    private void jMenuItemGestionMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionMatActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionMateria gM = new GestionMateria();
        gM.setVisible(true);
        escritorio.add(gM);
        escritorio.moveToFront(gM);
    }//GEN-LAST:event_jMenuItemGestionMatActionPerformed
    
    private void jMenuItemAxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAxMatActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaDeAlumnosPorMateria listado = new ConsultaDeAlumnosPorMateria();
        listado.setVisible(true);
        escritorio.add(listado);
        escritorio.moveToFront(listado);
    }//GEN-LAST:event_jMenuItemAxMatActionPerformed
    
    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        
    }//GEN-LAST:event_jMenuSalirActionPerformed
    
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem JItemGestionAlumno;
    private javax.swing.JMenuItem ManipulacionDeNotas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAxMat;
    private javax.swing.JMenuItem jMenuItemFormInscripciones;
    private javax.swing.JMenuItem jMenuItemGestionMat;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
