/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo46.Vistas;

import javax.swing.JOptionPane;
import universidadgrupo46.AccesoDeDatos.MateriaData;
import universidadgrupo46.Entidades.Materia;

/**
 *
 * @author simon
 */
public class GestionMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionMateria
     */
    public GestionMateria() {
        initComponents();
    }
    MateriaData mat = new MateriaData();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textCodigoMat = new javax.swing.JTextField();
        textNombreMat = new javax.swing.JTextField();
        textAñoMat = new javax.swing.JTextField();
        buttonBuscarMat = new javax.swing.JButton();
        buttonEstadoMat = new javax.swing.JRadioButton();
        buttonNuevo = new javax.swing.JButton();
        buttonEliminarMat = new javax.swing.JButton();
        buttonGuardarMat = new javax.swing.JButton();
        buttonSalirMat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año");

        jLabel5.setText("Estado");

        textCodigoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoMatActionPerformed(evt);
            }
        });

        buttonBuscarMat.setText("Buscar");
        buttonBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarMatActionPerformed(evt);
            }
        });

        buttonEstadoMat.setSelected(true);
        buttonEstadoMat.setEnabled(false);

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonEliminarMat.setText("Eliminar");
        buttonEliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarMatActionPerformed(evt);
            }
        });

        buttonGuardarMat.setText("Guardar");
        buttonGuardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarMatActionPerformed(evt);
            }
        });

        buttonSalirMat.setText("Salir");
        buttonSalirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(buttonEstadoMat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCodigoMat)
                                    .addComponent(textNombreMat)
                                    .addComponent(textAñoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addComponent(buttonBuscarMat))))
                    .addComponent(buttonNuevo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(buttonSalirMat)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonGuardarMat)
                            .addComponent(buttonEliminarMat))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCodigoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarMat)
                    .addComponent(buttonEliminarMat))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textNombreMat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textAñoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonGuardarMat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSalirMat)
                            .addComponent(buttonNuevo)))
                    .addComponent(buttonEstadoMat))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirMatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonSalirMatActionPerformed

    private void buttonGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarMatActionPerformed
        try {
            if (textNombreMat.getText().isEmpty() || textAñoMat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Le falta ingresar datos");
            } else {
                int año = Integer.parseInt(textAñoMat.getText());
                Materia materia = new Materia(textNombreMat.getText(), año, buttonEstadoMat.isSelected());
                mat.guardarMateria(materia);
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Caracteres ingresado en año son invalidos");
        }
    }//GEN-LAST:event_buttonGuardarMatActionPerformed

    private void textCodigoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoMatActionPerformed

    private void buttonBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarMatActionPerformed
        try {
            int c = Integer.parseInt(textCodigoMat.getText());
            Materia materia;
            materia = mat.buscarMateria(c);
            textNombreMat.setText(materia.getNombre());
            textAñoMat.setText(materia.getAnioMateria() + "");
            buttonEstadoMat.setSelected(materia.isEstado());
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Ingrese un codigo numerico para buscar una materia");
        } catch (NullPointerException np) {

        }
    }//GEN-LAST:event_buttonBuscarMatActionPerformed

    private void buttonEliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarMatActionPerformed
        try {
            int c = Integer.parseInt(textCodigoMat.getText());
            mat.eliminarMateria(c);
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Ingrese un dato valido para poder eliminar la materia");
        }
    }//GEN-LAST:event_buttonEliminarMatActionPerformed

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        textCodigoMat.setText("");
        textNombreMat.setText("");
        textAñoMat.setText("");
    }//GEN-LAST:event_buttonNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarMat;
    private javax.swing.JButton buttonEliminarMat;
    private javax.swing.JRadioButton buttonEstadoMat;
    private javax.swing.JButton buttonGuardarMat;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonSalirMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textAñoMat;
    private javax.swing.JTextField textCodigoMat;
    private javax.swing.JTextField textNombreMat;
    // End of variables declaration//GEN-END:variables
}
